apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-log
    receivers:
      - uid: default-log-receiver
        type: "email"
        disableResolveMessage: false
        settings:
          addresses: ""
          singleEmail: false
